In [15]:
import pandas as pd


sales_stations = pd.read_csv('../../data/Cleared_data/sales_stations.csv')
stations = pd.read_csv('../../data/Cleared_data/stations.csv', parse_dates=['created'])
sales= pd.read_csv('../../data/Cleared_data/sales.csv')

In [39]:
sales_stations

,station_id,date,daily_sales_count,created,partner_name,employee_name,cities
0,2581,2021-12-19,1.0,2024-03-11,Мегафон,Роман,Московская область
1,2540,2022-01-10,1.0,2024-02-26,Мегафон,Роман,Московская область
2,2878,2022-01-10,5.0,2024-03-28,Мегафон,Никита,Малый город
3,396,2022-02-14,1.0,2023-07-04,Мегафон,Роман,Московская область
4,2263,2022-02-14,1.0,2023-12-06,Максимус,Галина,Малый город
...,...,...,...,...,...,...,...
507618,3918,2026-09-16,1.0,2026-05-22,Beeline,Кирилл,Малый город
507619,3930,2026-09-16,1.0,2026-05-22,Beeline,Кирилл,Томск
507620,3974,2026-09-16,1.0,2026-08-14,Inventive Group,Екатерина,Омск
507621,4001,2026-09-16,2.0,2026-08-25,Inventive Group,Екатерина,Санкт-Петербург
507622,4012,2026-09-16,3.0,2026-08-27,Beeline,Екатерина,Владивосток

In [38]:
sales_stations[sales_stations['station_id'] == 2581].iloc[[0]]

,station_id,date,daily_sales_count,created,partner_name,employee_name,cities
0,2581,2021-12-19,1.0,2024-03-11,Мегафон,Роман,Московская область

In [40]:
def full_station(station_id):
    created = stations[stations['id'] == station_id].iloc[0]['created']
    last_sale = max(sales_stations[sales_stations['station_id'] == station_id]['date'])
    return last_sale


print(full_station(2581))

2026-09-15