# Sales

In [1]:
import pandas as pd
from IPython.display import display_html

sales = pd.read_csv('../../data/initial_data/ps_stats_initial.csv', parse_dates=['created', 'cut_time'])

In [2]:
sales

,id,created,cut_time,film_size,film_type,sale_type,time_zone,element_id,station_id
0,1426826,2026-09-16 08:33:01.203202,2026-09-16 11:32:58.067,PHONE,GLOSS,SALE,GMT+3:00,18828.0,2417.0
1,1426825,2026-09-16 08:32:53.050035,2026-09-16 11:32:50.449,PHONE,MATE,SALE,GMT+3:00,15795.0,2854.0
2,1426824,2026-09-16 08:31:40.230850,2026-09-16 13:31:40.030,PHONE,MATE,SALE,GMT+5:00,18268.0,438.0
3,1426823,2026-09-16 08:30:57.475055,2026-09-16 15:30:56.323,PHONE,MATE,DEFECT,GMT+7:00,16009.0,2265.0
4,1426822,2026-09-16 08:30:42.547585,2026-09-16 11:30:41.074,WATCH,GLOSS,SALE,GMT+3:00,17191.0,2224.0
...,...,...,...,...,...,...,...,...,...
1186807,240028,2023-07-27 13:15:28.000000,2023-07-27 07:15:25.918,PHONE,GLOSS,DEFECT,GMT 3:00,NaN,1.0
1186808,240027,2023-07-27 13:11:28.000000,2023-07-27 07:11:25.334,PHONE,GLOSS,DEFECT,GMT 5:00,NaN,586.0
1186809,240026,2023-07-26 23:50:06.000000,2023-07-26 15:22:41.211,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0
1186810,240025,2023-07-26 23:49:04.000000,2023-07-26 15:22:41.222,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0
1186811,240024,2023-07-26 23:43:23.000000,2023-07-26 15:22:41.233,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0

In [3]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1186812 entries, 0 to 1186811
Data columns (total 9 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   id          1186812 non-null  int64
 1   created     1186812 non-null  datetime64[us]
 2   cut_time    1186812 non-null  datetime64[us]
 3   film_size   1186812 non-null  str
 4   film_type   1186812 non-null  str
 5   sale_type   1186812 non-null  str
 6   time_zone   1186812 non-null  str
 7   element_id  919061 non-null   float64
 8   station_id  1186757 non-null  float64
dtypes: datetime64[us](2), float64(2), int64(1), str(4)
memory usage: 81.5 MB

###

In [4]:
df1_html = sales['film_type'].value_counts().to_frame().to_html()
df2_html = sales['film_size'].value_counts().to_frame().to_html()
df3_html = sales['sale_type'].value_counts().to_frame().to_html()

display_html(f'<div style="display:flex; gap:20px;">{df1_html}{df2_html}{df3_html}</div>', raw=True)

,count
film_type,
MATE,641082
GLOSS,538093
SPY,5909
NONE,964
COLOR,764
,count
film_size,
PHONE,1147628
WATCH,24044
LAPTOP,15140
,count
sale_type,
SALE,964371
DEFECT,144620
LEARN,58393
WARRANTY,16540
DEBUG,2888

# Stations

In [5]:
stations = pd.read_csv('../../data/initial_data/ps_stations_initial.csv')

In [6]:
stations

,id,address,code,created,login,partner_name,employee_name
0,1,"121601, Московская обл, Москва, Филевский б-р, 6",CODE,2023-07-04 15:57:36.000000,ily,Beeline,Галина
1,2,"141310, Московская обл, Сергиево-Посадский р-н...",L422,2023-07-04 15:58:42.000000,station1,Связной,Галина
2,3,"142600, Московская обл, Орехово-Зуево г, Якова...",L382,2023-07-04 15:58:42.000000,station2,Связной,Галина
3,4,"142500, Московская обл, Павлово-Посадский р-н,...",L387,2023-07-04 15:58:43.000000,station3,Связной,Галина
4,5,"141031, Московская обл, Мытищинский р-н, Алтуф...",L350,2023-07-04 15:58:43.000000,station4,Связной,Галина
...,...,...,...,...,...,...,...
4059,4063,"г. Сочи, ул. Новая заря, дом 7, ТЦ МореМолл",RSTR_СОЧ_МОРЕМОЛЛ,2026-09-15 12:01:48.469836,station4264,Inventive Group,Галина
4060,4064,"г. Сочи, ул. Новая заря, дом 7, ТЦ МореМолл SA...",SMSG_СОЧ_МОРЕМОЛЛ,2026-09-15 12:05:45.030168,station4265,Inventive Group,Галина
4061,4065,"г. Котельники, 1-й Покровский проезд, д.1, ТЦ...",RSTR_МСК_МЕГА_БЕЛАЯ_ДАЧА,2026-09-15 12:13:14.727116,station4266,Inventive Group,Галина
4062,4066,"г. Краснодар, ул. Головатого, д.313,(пом.1-044...",SMSG_КДР_ГАЛЕРЕЯ,2026-09-15 20:44:28.208919,station4267,Inventive Group,Галина
4063,4067,"Норильск, ул. нансена, д.70",WC92000,2026-09-16 07:07:31.370437,station4268,Beeline,Кирилл