# Соединяем станции и продажи
В записях подготовленной нами таблицы про продажи есть информация о том, какая станция делала продажи, а также у нас есть таблица со станциями и информацией о них. Первую таблицу нужно дополнить второй (именно с этой таблицей мы в итоге и будем работать).

In [36]:
import pandas as pd


stations = pd.read_csv('../../data/Cleared_data/stations.csv')
sales = pd.read_csv('../../data/Cleared_data/sales.csv')

In [37]:
sales

        station_id        date  daily_sales_count
0             1531  2023-07-27                2.0
1              287  2023-07-29                3.0
2              340  2023-07-29                2.0
3              596  2023-07-29                1.0
4              586  2023-07-30                2.0
...            ...         ...                ...
505371        3918  2026-09-16                1.0
505372        3930  2026-09-16                1.0
505373        3974  2026-09-16                1.0
505374        4001  2026-09-16                2.0
505375        4012  2026-09-16                4.0

[505376 rows x 3 columns]

In [38]:
stations

        id     created     partner_name employee_name              cities
0      277  2023-07-04          Мегафон     Екатерина     Санкт-Петербург
1      279  2023-07-04          Мегафон        Галина         Малый город
2      280  2023-07-04          Мегафон     Екатерина         Малый город
3      281  2023-07-04          Мегафон     Екатерина     Санкт-Петербург
4      283  2023-07-04          Мегафон         Роман  Московская область
...    ...         ...              ...           ...                 ...
2317  4027  2026-09-07  Inventive Group          Иван           Челябинск
2318  4049  2026-09-11  Inventive Group     Екатерина     Санкт-Петербург
2319  4052  2026-09-11  Inventive Group        Никита              Москва
2320  4054  2026-09-11  Inventive Group        Никита              Москва
2321  4055  2026-09-11  Inventive Group        Никита              Москва

[2322 rows x 5 columns]

In [39]:
sales_stations = sales.merge(stations, left_on='station_id', right_on='id', how='left')
sales_stations = sales_stations.drop(['id'], axis=1)

In [40]:
sales_stations.to_csv('../../data/Cleared_data/sales_stations.csv', index=False)